### ISSUE TITLE
intrinsic_matmul/matmul.c:2:10: fatal error: thead_matrix.h: No such file or directory

### ISSUE THREAD

**Issue by yelbuod** [XUANTIE-RV/riscv-matrix-extension-spec#9]
I run `./env.h` and get the error:
```
intrinsic_matmul/matmul.c:2:10: fatal error: thead_matrix.h: No such file or directory
    2 | #include <thead_matrix.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:26: intrinsic] Error 1
```
and I cannot find <thead_matrix.h> header file in the gcc or any other directory.

**Comment by QJtaibai** [comment]
fixed it with commit [e1a8f33]

**Comment by QJtaibai** [comment]
the latest toolchain can be found here    https://www.xrvm.cn/community/download?id=4333581795569242112

**Comment by yelbuod** [comment]
I found the <thread_matrix.h> header file and compile successfully via the toolchain in the link you provided. Thank you.
BTW, I found that the toolchain works with SPEC version 0.3, but not with version 0.4, because the matrix-scalar instructions were removed in SPEC version 0.4. Is that right?

**Comment by Grizzly-bear-ke** [comment]
> I found the <thread_matrix.h> header file and compile successfully via the toolchain in the link you provided. Thank you. BTW, I found that the toolchain works with SPEC version 0.3, but not with version 0.4, because the matrix-scalar instructions were removed in SPEC version 0.4. Is that right?

Where is the thread_matrix.h file?

**Comment by yelbuod** [comment]
> > I found the <thread_matrix.h> header file and compile successfully via the toolchain in the link you provided. Thank you. BTW, I found that the toolchain works with SPEC version 0.3, but not with version 0.4, because the matrix-scalar instructions were removed in SPEC version 0.4. Is that right?
> 
> Where is the thread_matrix.h file?

In the toolchain provided in the link above.
